apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${{ values.name }}
  namespace: ${{ values.name }}
  annotations:
    azure.workload.identity/client-id: ${{ values.workloadIdentityClientId | default('CHANGE_ME') }}
