apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: platform-vault
  namespace: ${{ values.name }}
spec:
  address: https://hashicorpvault.josua.com.pe
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: workload-auth
  namespace: ${{ values.name }}
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: ${{ values.name }}-${{ values.environment }}
    serviceAccount: ${{ values.name }}
    audiences:
      - vault
  vaultConnectionRef: platform-vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: app-config
  namespace: ${{ values.name }}
spec:
  type: kv-v2
  mount: kv
  path: ${{ values.vaultPath }}
  destination:
    name: app-config
    create: true
  vaultAuthRef: workload-auth
