apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{ values.name }}
  namespace: ${{ values.name }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ${{ values.name }}.${{ values.environment }}.josua.com.pe
      secretName: ${{ values.name }}-tls
  rules:
    - host: ${{ values.name }}.${{ values.environment }}.josua.com.pe
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ${{ values.name }}
                port:
                  number: 80
